---
- name: Configure Nagios to Monitor Tomcat
  hosts: all
  become: yes
  vars:
    nagios_config_dir: "/etc/nagios/conf.d"
    nagios_service_name: "Tomcat"
    tomcat_service_name: "tomcat"

  tasks:
    - name: Ensure Nagios is installed
      package:
        name: nagios
        state: present

    - name: Create Nagios configuration for Tomcat
      copy:
        dest: "{{ nagios_config_dir }}/tomcat.cfg"
        content: |
          define service {
              use                     generic-service
              host_name               localhost
              service_description     {{ nagios_service_name }}
              check_command           check_process!{{ tomcat_service_name }}
          }

    - name: Reload Nagios configuration
      service:
        name: nagios
        state: reloaded
